name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
    
  DeployDev:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: dev env
      url: 'vivid-poet-333222.uc.r.appspot.com '
    steps:
      - name: Deploy
        run: echo I am deploying! 
      - name: Pushes to another repository
        id: push_directory
        uses: abdullahokhan/googlerecommend434dev@main
        env:
         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'output'
          destination-github-username: 'abdullahokhan'
          destination-repository-name: 'googlerecommend434prod'
          user-email: abdullahovaiskhan1@gmail.com
          target-branch: main

    
